--bledy zamierzone

--klucz glowny
INSERT INTO Komenda
VALUES (1,'Kielce','Sloneczna','997a');

--unique
INSERT INTO Osoba
VALUES (OSOBASEQ.NEXTVAL,99022302198,'Kamil','Slimak',TO_DATE('23-02-99','DD-MM-YYYY'));

--not null

INSERT INTO Zatrzymani
VALUES(ZATRZYMANISEQ.NEXTVAL,null,TO_DATE('23-02-99','DD-MM-YYYY'));

--check

INSERT INTO Osoba
VALUES (OSOBASEQ.NEXTVAL,9,'Kamil','Slimak',TO_DATE('23-02-99','DD-MM-YYYY'));

--klucz obcy

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,200,ZATRZYMANISEQ.CURRVAL);


