--5
ALTER TABLE KOMENDA ADD TESTKOLUMN VARCHAR(5);

ALTER TABLE KOMENDA
MODIFY (TESTKOLUMN VARCHAR(5) UNIQUE);

ALTER TABLE KOMENDA
DROP UNIQUE (TESTKOLUMN);

ALTER TABLE KOMENDA
DROP (TESTKOLUMN);

