INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Kielce','Mickiewicza','22a');

INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Kielce','Krasickiego','2');

INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Rzeszow','Jana Pawla II','6');

INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Kielce','Niepodleglosci','13');

INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Krakow','Sloneczna','2');

INSERT INTO Komenda 
VALUES (komendaseq.nextval,'Warszawa','Kwiatowa','66b');

--------

INSERT INTO OSOBA
VALUES (osobaseq.nextval,99022302198,'Waldemara','Pawlak',TO_DATE('23-02-1999','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69020309792,'Jan','Kajetan',TO_DATE('03-02-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,59022302198,'Waldemar','Stawiak',TO_DATE('23-02-1959','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,49020309792,'Witold','Kajetan',TO_DATE('03-02-1949','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,97181207729,'Szymon','Rozek',TO_DATE('18-12-1997','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,97020309792,'Arkadiusz','Mazak',TO_DATE('03-02-1997','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111302332,'Wojtek','Dudel',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,79020309792,'Karolina','Hakier',TO_DATE('03-02-1979','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,99121201123,'Bartek','Doroszka',TO_DATE('12-12-1999','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,91022302198,'Michal','Pawlak',TO_DATE('23-02-1991','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,64020309792,'Pawel','Kajetan',TO_DATE('03-02-1964','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,87101207729,'Szymon','Mrozek',TO_DATE('10-12-1987','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,91020309792,'Zbyszek','Strazak',TO_DATE('03-02-1991','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,82111302332,'Wojtek','Krol',TO_DATE('13-11-1982','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,99020309092,'Karol','Florkiewicz',TO_DATE('03-02-1999','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,92121201123,'Bartek','Doroszka',TO_DATE('12-12-1992','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,99022502198,'Tomasz','Faranfal',TO_DATE('25-02-1999','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69020309732,'Krystyna','Kajetan',TO_DATE('03-02-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,97101217729,'Monika','Twarozek',TO_DATE('10-12-1997','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,97020309092,'Artur','Pasek',TO_DATE('03-02-1997','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111302335,'Wojtek','Lesnik',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,79020309000,'Karol','Kropyla',TO_DATE('03-02-1979','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,92121201120,'Kamil','Karolkiewicz',TO_DATE('12-12-1992','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,79020309779,'Karol','Kropyla',TO_DATE('03-02-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,92121201523,'Przemyslaw','Zoltkiewicz',TO_DATE('12-12-1992','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,79022302198,'Arek','Semafor',TO_DATE('23-02-1979','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,79020300792,'Karol','Detektyw',TO_DATE('03-02-1979','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,98101207729,'Szymon','Rozek',TO_DATE('10-12-1998','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,89020309792,'Arkadiusz','Straszak',TO_DATE('03-02-1989','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111302300,'Wojtek','Duda',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69120309792,'Karol','Hakier',TO_DATE('03-12-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,80121201123,'Bartlomiej','Doroszka',TO_DATE('12-12-1980','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,98101202229,'Zbyszek','Rozek',TO_DATE('10-12-1998','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,89010309702,'Tomasz','Straszak',TO_DATE('03-01-1989','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,51111302300,'Wojtek','Duda',TO_DATE('13-11-1951','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69120300292,'Karol','Kwintowski',TO_DATE('03-12-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,60121201123,'Przemek','Doroszka',TO_DATE('12-12-1960','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,78101203229,'Daniel','Froszek',TO_DATE('10-12-1978','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,89020301234,'Arkadiusz','Straszak',TO_DATE('03-02-1989','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111301233,'Wojtek','Duda',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69120304444,'Karol','Hakier',TO_DATE('03-12-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,80121206968,'Bartlomiej','Doroszka',TO_DATE('12-12-1980','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,78101203219,'Daniel','Proszek',TO_DATE('10-12-1978','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,89020301224,'Arkadiusz','Straszak',TO_DATE('03-02-1989','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111301263,'Wojtek','Duda',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69120304494,'Karol','Hakier',TO_DATE('03-12-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,80121206908,'Bartlomiej','Doroszka',TO_DATE('12-12-1980','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,78101203002,'Janek','Froszek',TO_DATE('10-12-1978','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,89020301003,'Arkadiusz','Straszak',TO_DATE('03-02-1989','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,71111301004,'Wojtek','Duda',TO_DATE('13-11-1971','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,69120304005,'Karol','Hakier',TO_DATE('03-12-1969','DD-MM-YYYY'));

INSERT INTO OSOBA
VALUES (osobaseq.nextval,80121206006,'Bartlomiej','Doroszka',TO_DATE('12-12-1980','DD-MM-YYYY'));


-----

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'RTA 2302','Honda','Civic 5D',500203);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'RTA C2331','Honda','Civic 5D',200321);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'KR KS02','Toyota','Corolla',2203);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'KR 3321A','Toyota','Camry',120001);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK Z302','Fiat','Panda',922203);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK 2302','Honda','Civic 5D',40203);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK AA02','Honda','Civic 5D',10203);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK 12ZA2','Skoda','Octavia',104403);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK AAZ02','Renault','Megane RS',12299);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'TK 1OZA2','Fiat','Cinquecento',999999);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'WE AH1N1','Fiat','Punto Evo',92321);

INSERT INTO Radiowozy
VALUES (RADIOWOZYSEQ.NEXTVAL,'WE S112G','Fiat','Punto Evo',12321);

--

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,1,1,6,2000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,2,1,6,2000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,3,1,7,8000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,5,1,8,12000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,4,2,5,2000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,6,2,10,2500);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,7,4,9,4000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,8,4,9,4000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,9,3,1,4000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,10,3,1,2100);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,11,3,2,3333);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,12,5,3,10000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,13,5,3,2222);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,14,5,3,4000);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,15,5,4,5200);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,16,5,4,3350);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,17,6,11,2500);

INSERT INTO Policjanci
VALUES (POLICJANCISEQ.NEXTVAL,18,6,12,7200);

-----

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,19,1,5000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,20,1,2000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,21,2,2000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,22,3,2500);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,23,4,3000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,24,4,3000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,25,4,3000);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,26,5,2550);

INSERT INTO Pracownicy_Adm
VALUES (PRACOWNICY_ADMSEQ.NEXTVAL,27,6,5220);

---

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,28);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,29);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-12-2002','DD-MM-YYYY'),zglaszajacyseq.currval,1);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,30);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,31);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-12-2012','DD-MM-YYYY'),zglaszajacyseq.currval,1);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,32);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,33);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-12-2012','DD-MM-YYYY'),zglaszajacyseq.currval,2);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,34);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,35);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-02-2012','DD-MM-YYYY'),zglaszajacyseq.currval,3);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,36);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,37);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-11-2012','DD-MM-YYYY'),zglaszajacyseq.currval,4);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,38);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,39);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-12-2014','DD-MM-YYYY'),zglaszajacyseq.currval,5);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,40);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,41);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('11-12-2012','DD-MM-YYYY'),zglaszajacyseq.currval,6);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

INSERT INTO Zglaszajacy
VALUES (ZGLASZAJACYSEQ.NEXTVAL,42);

INSERT INTO Poszukiwani
VALUES(POSZUKIWANISEQ.NEXTVAL,43);

INSERT INTO ZGLOSZENIA
VALUES (ZGLOSZENIASEQ.NEXTVAL,TO_DATE('01-12-2012','DD-MM-YYYY'),zglaszajacyseq.currval,6);

INSERT INTO ZGLOSZENIAPOSZUKIWANI
VALUES (ZGLOSZENIAPOSZUKIWANISEQ.NEXTVAL,ZGLOSZENIASEQ.CURRVAL,POSZUKIWANISEQ.CURRVAL);

---
INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Kradziez');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,44,TO_DATE('01-12-1999','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,45,TO_DATE('01-12-1999','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,46,TO_DATE('01-12-1999','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);


INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Morderstwo');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,47,TO_DATE('01-02-2018','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Sprzedaz alkoholu nieletnim');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,48,TO_DATE('01-12-2009','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Gwalt');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,49,TO_DATE('21-12-1999','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Porwanie');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,50,TO_DATE('01-12-2017','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Posiadanie narkotykow');

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,51,TO_DATE('21-12-2003','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO ZATRZYMANI
VALUES (ZATRZYMANISEQ.NEXTVAL,52,TO_DATE('01-12-2009','DD-MM-YYYY'));

INSERT INTO WYKROCZENIAZATRZYMANI
VALUES (WYKROCZENIAZATRZYMANISEQ.NEXTVAL,WYKROCZENIASEQ.CURRVAL,ZATRZYMANISEQ.CURRVAL);

INSERT INTO WYKROCZENIA
VALUES (WYKROCZENIASEQ.NEXTVAL,'Pobicie');

INSERT INTO OSOBA
VALUES (OSOBASEQ.NEXTVAL,90082132142,'Karol','Bugabuga',TO_DATE('21-08-1990','DD-MM-YYYY'));

INSERT INTO POLICJANCI
VALUES(POLICJANCISEQ.NEXTVAL,OSOBASEQ.CURRVAL,KOMENDASEQ.CURRVAL,RADIOWOZYSEQ.CURRVAL,12000);

