SET SERVEROUTPUT ON;
/
DROP TABLE KOMENDA_KOPIA;
CREATE TABLE KOMENDA_KOPIA AS SELECT * FROM KOMENDA;
/
CREATE OR REPLACE TRIGGER KOPIA_KOMENDA_TRIGGER
AFTER INSERT OR DELETE OR UPDATE ON KOMENDA     
FOR EACH ROW    
BEGIN
CASE
WHEN INSERTING THEN
--INSERT INTO komenda_kopia VALUES(:new.id_komendy,:new.miejscowosc,:new.ulica,:new.nr_lokalu);
SELECT ID_KOMENDY,MIEJSCOWOSC,ULICA,NR_LOKALU INTO KOMENDA
WHEN DELETING THEN
DELETE FROM KOMENDA_KOPIA WHERE :OLD.ID_KOMENDY = ID_KOMENDY;
WHEN UPDATING THEN
UPDATE KOMENDA_KOPIA SET ID_KOMENDY = :NEW.ID_KOMENDY, MIEJSCOWOSC = :NEW.MIEJSCOWOSC, ULICA = :NEW.ULICA, NR_LOKALU = :NEW.NR_LOKALU
WHERE ID_KOMENDY = :OLD.ID_KOMENDY;
END CASE;
END;
/
SELECT *FROM KOMENDA;
SELECT *FROM KOMENDA_KOPIA;

--2
DROP SEQUENCE POLICJANCI_LOGSEQ;
CREATE SEQUENCE POLICJANCI_LOGSEQ;
/
CREATE OR REPLACE TRIGGER TRIGGER_POLICJANCI_LOG
AFTER INSERT OR DELETE OR UPDATE ON POLICJANCI
FOR EACH ROW
DECLARE
OPERATION VARCHAR2(20);
BEGIN
CASE
WHEN INSERTING THEN
OPERATION:='INSERT INTO';
WHEN UPDATING THEN
OPERATION:='UPDATE';
WHEN DELETING THEN
OPERATION:='DELETE';
END CASE;
INSERT INTO POLICJANCI_LOG VALUES(POLICJANCI_LOGSEQ.NEXTVAL,SYSDATE,OPERATION);
END;
/
SELECT * FROM POLICJANCI_LOG;
--3 za male zarobki

CREATE OR REPLACE TRIGGER MALE_ZAROBKI_TRIGGER
AFTER INSERT ON POLICJANCI
FOR EACH ROW
BEGIN 
IF(:NEW.WYNAGRODZENIE < 1500)
THEN
RAISE_APPLICATION_ERROR(-20001,'Wynagrodzenie mniejsze od placy minimalnej');
END IF;
END;
/
--procedura do dodawania policjanta do testowania
.
--4 za duze wydatki komendy
/
CREATE OR REPLACE TRIGGER WYDATKI_KOMENDY_TRIGGER
BEFORE INSERT ON POLICJANCI
FOR EACH ROW
DECLARE
SUMA_WYNAGRODZEN NUMBER(7);
BEGIN 
SELECT SUM(WYNAGRODZENIE)
INTO SUMA_WYNAGRODZEN
FROM POLICJANCI
WHERE :NEW.ID_KOMENDY = ID_KOMENDY;
IF(SUMA_WYNAGRODZEN + :NEW.WYNAGRODZENIE > 100000)
THEN
SUMA_WYNAGRODZEN := SUMA_WYNAGRODZEN + :NEW.WYNAGRODZENIE;
RAISE_APPLICATION_ERROR(-20000,'Komenda ma za duze wydatki na wynagrodzenia! '||SUMA_WYNAGRODZEN);
END IF;
END;
/
--procedura do dodawania policjanta do testowania
/
--5
CREATE OR REPLACE TRIGGER POLICJANCI_USUWANIE
AFTER DELETE ON POLICJANCI
FOR EACH ROW
DECLARE
L_CNT NUMBER(2);
BEGIN
SELECT COUNT(*) INTO L_CNT FROM USER_TABLES WHERE TABLE_NAME='OSOBA_KOPIA';
IF L_CNT > 0 THEN
EXECUTE IMMEDIATE
'DELETE FROM OSOBA_kopia WHERE osoba_kopia.id_osoby ='||:old.id_osoby;
END IF;
DELETE FROM OSOBA WHERE OSOBA.ID_OSOBY = :OLD.ID_OSOBY;
END;
/
SELECT * FROM POLICJANCI;
SELECT * FROM OSOBA;
SELECT * FROM OSOBA_KOPIA;

DELETE FROM POLICJANCI WHERE ID_POLICJANTA = 1;

